# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'
source 'https://github.com/Lidalu/QIMOpenSSL.git'
source 'git@github.com:CocoaPods/Specs.git'

target 'QIMSDK' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QIMSDK

#    pod 'QIMUIKit', path: './../QIMUIKit'
#    pod 'QIMIPadKit', path: './../QIMIPadKit'
#    pod 'QIMUIVendorKit', path: './../QIMUIVendorKit'

#    https://github.com/CocoaPods/Specs/blob/master/Specs/3/6/0/Crashlytics/3.1.0/Crashlytics.podspec.json
#    https://github.com/sleepio/cocoapods-fabric/blob/master/Fabric.podspec
#    https://github.com/sleepio/cocoapods-fabric
#    pod 'QIMKitVendor', path: './../QIMKitVendor'
#    pod 'QIMGeneralModule', path: './../QIMGeneralModule'
#    pod 'QIMCommon', path: './../QIMCommon'
#    pod 'QIMCommonCategories', path: './../QIMCommonCategories'
#    pod 'QIMDataBase', path: './../QIMDataBase'

    pod 'MJRefresh'
    pod 'YLGIFImage'
    pod 'SwipeBack'
    pod 'SwipeTableView'
    pod 'LCActionSheet'
    pod 'MDHTMLLabel'
    pod 'MMMarkdown'
    pod 'MGSwipeTableCell'
    pod 'MBProgressHUD', '~> 0.9'
    pod 'DACircularProgress', '~> 2.3'
    pod 'SDWebImage', '~> 3.7', '!= 3.7.2'
    pod 'NJKWebViewProgress'
    pod 'AMapSearch'
    pod 'AMapLocation'
    pod 'AMap3DMap'
    pod 'MMPickerView'
    pod 'SCLAlertView-Objective-C'

    pod 'yoga', :path => './../node_modules/react-native/ReactCommon/yoga'
    # Third party deps podspec link
    #  pod 'DoubleConversion', :podspec => './../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    #  pod 'glog', :podspec => './../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => './../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
    pod 'React',
    :path => './../node_modules/react-native',
    :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration',
    'RCTAnimation',
    'ART',
    'RCTGeolocation',
    'RCTActionSheet',
    'DevSupport',
    'CxxBridge',
    # 添加其他你想在工程中使用的依赖。
    ]
    #pod "React"
    #pod "React/RCTText"
    #pod 'react-native-cookies', :path => './node_modules/react-native-cookies'
    pod 'react-native-image-picker', :path => './../node_modules/react-native-image-picker'
    pod 'RNSVG', :path => './../node_modules/react-native-svg'
end
